# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import primitives_pb2 as primitives__pb2


_GETINFOREQUEST = DESCRIPTOR.message_types_by_name['GetinfoRequest']
_GETINFORESPONSE = DESCRIPTOR.message_types_by_name['GetinfoResponse']
_GETINFOOUR_FEATURES = DESCRIPTOR.message_types_by_name['GetinfoOur_features']
_GETINFOADDRESS = DESCRIPTOR.message_types_by_name['GetinfoAddress']
_GETINFOBINDING = DESCRIPTOR.message_types_by_name['GetinfoBinding']
_LISTPEERSREQUEST = DESCRIPTOR.message_types_by_name['ListpeersRequest']
_LISTPEERSRESPONSE = DESCRIPTOR.message_types_by_name['ListpeersResponse']
_LISTPEERSPEERS = DESCRIPTOR.message_types_by_name['ListpeersPeers']
_LISTPEERSPEERSLOG = DESCRIPTOR.message_types_by_name['ListpeersPeersLog']
_LISTFUNDSREQUEST = DESCRIPTOR.message_types_by_name['ListfundsRequest']
_LISTFUNDSRESPONSE = DESCRIPTOR.message_types_by_name['ListfundsResponse']
_LISTFUNDSOUTPUTS = DESCRIPTOR.message_types_by_name['ListfundsOutputs']
_LISTFUNDSCHANNELS = DESCRIPTOR.message_types_by_name['ListfundsChannels']
_SENDPAYREQUEST = DESCRIPTOR.message_types_by_name['SendpayRequest']
_SENDPAYRESPONSE = DESCRIPTOR.message_types_by_name['SendpayResponse']
_SENDPAYROUTE = DESCRIPTOR.message_types_by_name['SendpayRoute']
_LISTCHANNELSREQUEST = DESCRIPTOR.message_types_by_name['ListchannelsRequest']
_LISTCHANNELSRESPONSE = DESCRIPTOR.message_types_by_name['ListchannelsResponse']
_LISTCHANNELSCHANNELS = DESCRIPTOR.message_types_by_name['ListchannelsChannels']
_ADDGOSSIPREQUEST = DESCRIPTOR.message_types_by_name['AddgossipRequest']
_ADDGOSSIPRESPONSE = DESCRIPTOR.message_types_by_name['AddgossipResponse']
_AUTOCLEANINVOICEREQUEST = DESCRIPTOR.message_types_by_name['AutocleaninvoiceRequest']
_AUTOCLEANINVOICERESPONSE = DESCRIPTOR.message_types_by_name['AutocleaninvoiceResponse']
_CHECKMESSAGEREQUEST = DESCRIPTOR.message_types_by_name['CheckmessageRequest']
_CHECKMESSAGERESPONSE = DESCRIPTOR.message_types_by_name['CheckmessageResponse']
_CLOSEREQUEST = DESCRIPTOR.message_types_by_name['CloseRequest']
_CLOSERESPONSE = DESCRIPTOR.message_types_by_name['CloseResponse']
_CONNECTREQUEST = DESCRIPTOR.message_types_by_name['ConnectRequest']
_CONNECTRESPONSE = DESCRIPTOR.message_types_by_name['ConnectResponse']
_CONNECTADDRESS = DESCRIPTOR.message_types_by_name['ConnectAddress']
_CREATEINVOICEREQUEST = DESCRIPTOR.message_types_by_name['CreateinvoiceRequest']
_CREATEINVOICERESPONSE = DESCRIPTOR.message_types_by_name['CreateinvoiceResponse']
_DATASTOREREQUEST = DESCRIPTOR.message_types_by_name['DatastoreRequest']
_DATASTORERESPONSE = DESCRIPTOR.message_types_by_name['DatastoreResponse']
_CREATEONIONREQUEST = DESCRIPTOR.message_types_by_name['CreateonionRequest']
_CREATEONIONRESPONSE = DESCRIPTOR.message_types_by_name['CreateonionResponse']
_CREATEONIONHOPS = DESCRIPTOR.message_types_by_name['CreateonionHops']
_DELDATASTOREREQUEST = DESCRIPTOR.message_types_by_name['DeldatastoreRequest']
_DELDATASTORERESPONSE = DESCRIPTOR.message_types_by_name['DeldatastoreResponse']
_DELEXPIREDINVOICEREQUEST = DESCRIPTOR.message_types_by_name['DelexpiredinvoiceRequest']
_DELEXPIREDINVOICERESPONSE = DESCRIPTOR.message_types_by_name['DelexpiredinvoiceResponse']
_DELINVOICEREQUEST = DESCRIPTOR.message_types_by_name['DelinvoiceRequest']
_DELINVOICERESPONSE = DESCRIPTOR.message_types_by_name['DelinvoiceResponse']
_INVOICEREQUEST = DESCRIPTOR.message_types_by_name['InvoiceRequest']
_INVOICERESPONSE = DESCRIPTOR.message_types_by_name['InvoiceResponse']
_LISTDATASTOREREQUEST = DESCRIPTOR.message_types_by_name['ListdatastoreRequest']
_LISTDATASTORERESPONSE = DESCRIPTOR.message_types_by_name['ListdatastoreResponse']
_LISTDATASTOREDATASTORE = DESCRIPTOR.message_types_by_name['ListdatastoreDatastore']
_LISTINVOICESREQUEST = DESCRIPTOR.message_types_by_name['ListinvoicesRequest']
_LISTINVOICESRESPONSE = DESCRIPTOR.message_types_by_name['ListinvoicesResponse']
_LISTINVOICESINVOICES = DESCRIPTOR.message_types_by_name['ListinvoicesInvoices']
_SENDONIONREQUEST = DESCRIPTOR.message_types_by_name['SendonionRequest']
_SENDONIONRESPONSE = DESCRIPTOR.message_types_by_name['SendonionResponse']
_SENDONIONFIRST_HOP = DESCRIPTOR.message_types_by_name['SendonionFirst_hop']
_LISTSENDPAYSREQUEST = DESCRIPTOR.message_types_by_name['ListsendpaysRequest']
_LISTSENDPAYSRESPONSE = DESCRIPTOR.message_types_by_name['ListsendpaysResponse']
_LISTSENDPAYSPAYMENTS = DESCRIPTOR.message_types_by_name['ListsendpaysPayments']
_LISTTRANSACTIONSREQUEST = DESCRIPTOR.message_types_by_name['ListtransactionsRequest']
_LISTTRANSACTIONSRESPONSE = DESCRIPTOR.message_types_by_name['ListtransactionsResponse']
_LISTTRANSACTIONSTRANSACTIONS = DESCRIPTOR.message_types_by_name['ListtransactionsTransactions']
_LISTTRANSACTIONSTRANSACTIONSINPUTS = DESCRIPTOR.message_types_by_name['ListtransactionsTransactionsInputs']
_LISTTRANSACTIONSTRANSACTIONSOUTPUTS = DESCRIPTOR.message_types_by_name['ListtransactionsTransactionsOutputs']
_PAYREQUEST = DESCRIPTOR.message_types_by_name['PayRequest']
_PAYRESPONSE = DESCRIPTOR.message_types_by_name['PayResponse']
_LISTNODESREQUEST = DESCRIPTOR.message_types_by_name['ListnodesRequest']
_LISTNODESRESPONSE = DESCRIPTOR.message_types_by_name['ListnodesResponse']
_LISTNODESNODES = DESCRIPTOR.message_types_by_name['ListnodesNodes']
_LISTNODESNODESADDRESSES = DESCRIPTOR.message_types_by_name['ListnodesNodesAddresses']
_WAITANYINVOICEREQUEST = DESCRIPTOR.message_types_by_name['WaitanyinvoiceRequest']
_WAITANYINVOICERESPONSE = DESCRIPTOR.message_types_by_name['WaitanyinvoiceResponse']
_WAITINVOICEREQUEST = DESCRIPTOR.message_types_by_name['WaitinvoiceRequest']
_WAITINVOICERESPONSE = DESCRIPTOR.message_types_by_name['WaitinvoiceResponse']
_WAITSENDPAYREQUEST = DESCRIPTOR.message_types_by_name['WaitsendpayRequest']
_WAITSENDPAYRESPONSE = DESCRIPTOR.message_types_by_name['WaitsendpayResponse']
_NEWADDRREQUEST = DESCRIPTOR.message_types_by_name['NewaddrRequest']
_NEWADDRRESPONSE = DESCRIPTOR.message_types_by_name['NewaddrResponse']
_WITHDRAWREQUEST = DESCRIPTOR.message_types_by_name['WithdrawRequest']
_WITHDRAWRESPONSE = DESCRIPTOR.message_types_by_name['WithdrawResponse']
_KEYSENDREQUEST = DESCRIPTOR.message_types_by_name['KeysendRequest']
_KEYSENDRESPONSE = DESCRIPTOR.message_types_by_name['KeysendResponse']
_KEYSENDEXTRATLVS = DESCRIPTOR.message_types_by_name['KeysendExtratlvs']
_FUNDPSBTREQUEST = DESCRIPTOR.message_types_by_name['FundpsbtRequest']
_FUNDPSBTRESPONSE = DESCRIPTOR.message_types_by_name['FundpsbtResponse']
_FUNDPSBTRESERVATIONS = DESCRIPTOR.message_types_by_name['FundpsbtReservations']
_SENDPSBTREQUEST = DESCRIPTOR.message_types_by_name['SendpsbtRequest']
_SENDPSBTRESPONSE = DESCRIPTOR.message_types_by_name['SendpsbtResponse']
_SIGNPSBTREQUEST = DESCRIPTOR.message_types_by_name['SignpsbtRequest']
_SIGNPSBTRESPONSE = DESCRIPTOR.message_types_by_name['SignpsbtResponse']
_UTXOPSBTREQUEST = DESCRIPTOR.message_types_by_name['UtxopsbtRequest']
_UTXOPSBTRESPONSE = DESCRIPTOR.message_types_by_name['UtxopsbtResponse']
_UTXOPSBTRESERVATIONS = DESCRIPTOR.message_types_by_name['UtxopsbtReservations']
_TXDISCARDREQUEST = DESCRIPTOR.message_types_by_name['TxdiscardRequest']
_TXDISCARDRESPONSE = DESCRIPTOR.message_types_by_name['TxdiscardResponse']
_TXPREPAREREQUEST = DESCRIPTOR.message_types_by_name['TxprepareRequest']
_TXPREPARERESPONSE = DESCRIPTOR.message_types_by_name['TxprepareResponse']
_TXSENDREQUEST = DESCRIPTOR.message_types_by_name['TxsendRequest']
_TXSENDRESPONSE = DESCRIPTOR.message_types_by_name['TxsendResponse']
_DISCONNECTREQUEST = DESCRIPTOR.message_types_by_name['DisconnectRequest']
_DISCONNECTRESPONSE = DESCRIPTOR.message_types_by_name['DisconnectResponse']
_FEERATESREQUEST = DESCRIPTOR.message_types_by_name['FeeratesRequest']
_FEERATESRESPONSE = DESCRIPTOR.message_types_by_name['FeeratesResponse']
_FEERATESPERKB = DESCRIPTOR.message_types_by_name['FeeratesPerkb']
_FEERATESPERKW = DESCRIPTOR.message_types_by_name['FeeratesPerkw']
_FEERATESONCHAIN_FEE_ESTIMATES = DESCRIPTOR.message_types_by_name['FeeratesOnchain_fee_estimates']
_FUNDCHANNELREQUEST = DESCRIPTOR.message_types_by_name['FundchannelRequest']
_FUNDCHANNELRESPONSE = DESCRIPTOR.message_types_by_name['FundchannelResponse']
_GETROUTEREQUEST = DESCRIPTOR.message_types_by_name['GetrouteRequest']
_GETROUTERESPONSE = DESCRIPTOR.message_types_by_name['GetrouteResponse']
_GETROUTEROUTE = DESCRIPTOR.message_types_by_name['GetrouteRoute']
_LISTFORWARDSREQUEST = DESCRIPTOR.message_types_by_name['ListforwardsRequest']
_LISTFORWARDSRESPONSE = DESCRIPTOR.message_types_by_name['ListforwardsResponse']
_LISTFORWARDSFORWARDS = DESCRIPTOR.message_types_by_name['ListforwardsForwards']
_LISTPAYSREQUEST = DESCRIPTOR.message_types_by_name['ListpaysRequest']
_LISTPAYSRESPONSE = DESCRIPTOR.message_types_by_name['ListpaysResponse']
_LISTPAYSPAYS = DESCRIPTOR.message_types_by_name['ListpaysPays']
_PINGREQUEST = DESCRIPTOR.message_types_by_name['PingRequest']
_PINGRESPONSE = DESCRIPTOR.message_types_by_name['PingResponse']
_SIGNMESSAGEREQUEST = DESCRIPTOR.message_types_by_name['SignmessageRequest']
_SIGNMESSAGERESPONSE = DESCRIPTOR.message_types_by_name['SignmessageResponse']
_STOPREQUEST = DESCRIPTOR.message_types_by_name['StopRequest']
_STOPRESPONSE = DESCRIPTOR.message_types_by_name['StopResponse']
_GETINFOADDRESS_GETINFOADDRESSTYPE = _GETINFOADDRESS.enum_types_by_name['GetinfoAddressType']
_GETINFOBINDING_GETINFOBINDINGTYPE = _GETINFOBINDING.enum_types_by_name['GetinfoBindingType']
_LISTPEERSPEERSLOG_LISTPEERSPEERSLOGTYPE = _LISTPEERSPEERSLOG.enum_types_by_name['ListpeersPeersLogType']
_LISTFUNDSOUTPUTS_LISTFUNDSOUTPUTSSTATUS = _LISTFUNDSOUTPUTS.enum_types_by_name['ListfundsOutputsStatus']
_SENDPAYRESPONSE_SENDPAYSTATUS = _SENDPAYRESPONSE.enum_types_by_name['SendpayStatus']
_CLOSERESPONSE_CLOSETYPE = _CLOSERESPONSE.enum_types_by_name['CloseType']
_CONNECTRESPONSE_CONNECTDIRECTION = _CONNECTRESPONSE.enum_types_by_name['ConnectDirection']
_CONNECTADDRESS_CONNECTADDRESSTYPE = _CONNECTADDRESS.enum_types_by_name['ConnectAddressType']
_CREATEINVOICERESPONSE_CREATEINVOICESTATUS = _CREATEINVOICERESPONSE.enum_types_by_name['CreateinvoiceStatus']
_DATASTOREREQUEST_DATASTOREMODE = _DATASTOREREQUEST.enum_types_by_name['DatastoreMode']
_DELINVOICEREQUEST_DELINVOICESTATUS = _DELINVOICEREQUEST.enum_types_by_name['DelinvoiceStatus']
_DELINVOICERESPONSE_DELINVOICESTATUS = _DELINVOICERESPONSE.enum_types_by_name['DelinvoiceStatus']
_LISTINVOICESINVOICES_LISTINVOICESINVOICESSTATUS = _LISTINVOICESINVOICES.enum_types_by_name['ListinvoicesInvoicesStatus']
_SENDONIONRESPONSE_SENDONIONSTATUS = _SENDONIONRESPONSE.enum_types_by_name['SendonionStatus']
_LISTSENDPAYSREQUEST_LISTSENDPAYSSTATUS = _LISTSENDPAYSREQUEST.enum_types_by_name['ListsendpaysStatus']
_LISTSENDPAYSPAYMENTS_LISTSENDPAYSPAYMENTSSTATUS = _LISTSENDPAYSPAYMENTS.enum_types_by_name['ListsendpaysPaymentsStatus']
_LISTTRANSACTIONSTRANSACTIONSINPUTS_LISTTRANSACTIONSTRANSACTIONSINPUTSTYPE = _LISTTRANSACTIONSTRANSACTIONSINPUTS.enum_types_by_name['ListtransactionsTransactionsInputsType']
_LISTTRANSACTIONSTRANSACTIONSOUTPUTS_LISTTRANSACTIONSTRANSACTIONSOUTPUTSTYPE = _LISTTRANSACTIONSTRANSACTIONSOUTPUTS.enum_types_by_name['ListtransactionsTransactionsOutputsType']
_PAYRESPONSE_PAYSTATUS = _PAYRESPONSE.enum_types_by_name['PayStatus']
_LISTNODESNODESADDRESSES_LISTNODESNODESADDRESSESTYPE = _LISTNODESNODESADDRESSES.enum_types_by_name['ListnodesNodesAddressesType']
_WAITANYINVOICERESPONSE_WAITANYINVOICESTATUS = _WAITANYINVOICERESPONSE.enum_types_by_name['WaitanyinvoiceStatus']
_WAITINVOICERESPONSE_WAITINVOICESTATUS = _WAITINVOICERESPONSE.enum_types_by_name['WaitinvoiceStatus']
_WAITSENDPAYRESPONSE_WAITSENDPAYSTATUS = _WAITSENDPAYRESPONSE.enum_types_by_name['WaitsendpayStatus']
_NEWADDRREQUEST_NEWADDRADDRESSTYPE = _NEWADDRREQUEST.enum_types_by_name['NewaddrAddresstype']
_KEYSENDRESPONSE_KEYSENDSTATUS = _KEYSENDRESPONSE.enum_types_by_name['KeysendStatus']
_FEERATESREQUEST_FEERATESSTYLE = _FEERATESREQUEST.enum_types_by_name['FeeratesStyle']
_GETROUTEROUTE_GETROUTEROUTESTYLE = _GETROUTEROUTE.enum_types_by_name['GetrouteRouteStyle']
_LISTFORWARDSREQUEST_LISTFORWARDSSTATUS = _LISTFORWARDSREQUEST.enum_types_by_name['ListforwardsStatus']
_LISTFORWARDSFORWARDS_LISTFORWARDSFORWARDSSTATUS = _LISTFORWARDSFORWARDS.enum_types_by_name['ListforwardsForwardsStatus']
_LISTFORWARDSFORWARDS_LISTFORWARDSFORWARDSSTYLE = _LISTFORWARDSFORWARDS.enum_types_by_name['ListforwardsForwardsStyle']
_LISTPAYSREQUEST_LISTPAYSSTATUS = _LISTPAYSREQUEST.enum_types_by_name['ListpaysStatus']
_LISTPAYSPAYS_LISTPAYSPAYSSTATUS = _LISTPAYSPAYS.enum_types_by_name['ListpaysPaysStatus']
GetinfoRequest = _reflection.GeneratedProtocolMessageType('GetinfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETINFOREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.GetinfoRequest)
  })
_sym_db.RegisterMessage(GetinfoRequest)

GetinfoResponse = _reflection.GeneratedProtocolMessageType('GetinfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETINFORESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.GetinfoResponse)
  })
_sym_db.RegisterMessage(GetinfoResponse)

GetinfoOur_features = _reflection.GeneratedProtocolMessageType('GetinfoOur_features', (_message.Message,), {
  'DESCRIPTOR' : _GETINFOOUR_FEATURES,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.GetinfoOur_features)
  })
_sym_db.RegisterMessage(GetinfoOur_features)

GetinfoAddress = _reflection.GeneratedProtocolMessageType('GetinfoAddress', (_message.Message,), {
  'DESCRIPTOR' : _GETINFOADDRESS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.GetinfoAddress)
  })
_sym_db.RegisterMessage(GetinfoAddress)

GetinfoBinding = _reflection.GeneratedProtocolMessageType('GetinfoBinding', (_message.Message,), {
  'DESCRIPTOR' : _GETINFOBINDING,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.GetinfoBinding)
  })
_sym_db.RegisterMessage(GetinfoBinding)

ListpeersRequest = _reflection.GeneratedProtocolMessageType('ListpeersRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTPEERSREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListpeersRequest)
  })
_sym_db.RegisterMessage(ListpeersRequest)

ListpeersResponse = _reflection.GeneratedProtocolMessageType('ListpeersResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTPEERSRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListpeersResponse)
  })
_sym_db.RegisterMessage(ListpeersResponse)

ListpeersPeers = _reflection.GeneratedProtocolMessageType('ListpeersPeers', (_message.Message,), {
  'DESCRIPTOR' : _LISTPEERSPEERS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListpeersPeers)
  })
_sym_db.RegisterMessage(ListpeersPeers)

ListpeersPeersLog = _reflection.GeneratedProtocolMessageType('ListpeersPeersLog', (_message.Message,), {
  'DESCRIPTOR' : _LISTPEERSPEERSLOG,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListpeersPeersLog)
  })
_sym_db.RegisterMessage(ListpeersPeersLog)

ListfundsRequest = _reflection.GeneratedProtocolMessageType('ListfundsRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTFUNDSREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListfundsRequest)
  })
_sym_db.RegisterMessage(ListfundsRequest)

ListfundsResponse = _reflection.GeneratedProtocolMessageType('ListfundsResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTFUNDSRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListfundsResponse)
  })
_sym_db.RegisterMessage(ListfundsResponse)

ListfundsOutputs = _reflection.GeneratedProtocolMessageType('ListfundsOutputs', (_message.Message,), {
  'DESCRIPTOR' : _LISTFUNDSOUTPUTS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListfundsOutputs)
  })
_sym_db.RegisterMessage(ListfundsOutputs)

ListfundsChannels = _reflection.GeneratedProtocolMessageType('ListfundsChannels', (_message.Message,), {
  'DESCRIPTOR' : _LISTFUNDSCHANNELS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListfundsChannels)
  })
_sym_db.RegisterMessage(ListfundsChannels)

SendpayRequest = _reflection.GeneratedProtocolMessageType('SendpayRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDPAYREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.SendpayRequest)
  })
_sym_db.RegisterMessage(SendpayRequest)

SendpayResponse = _reflection.GeneratedProtocolMessageType('SendpayResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDPAYRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.SendpayResponse)
  })
_sym_db.RegisterMessage(SendpayResponse)

SendpayRoute = _reflection.GeneratedProtocolMessageType('SendpayRoute', (_message.Message,), {
  'DESCRIPTOR' : _SENDPAYROUTE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.SendpayRoute)
  })
_sym_db.RegisterMessage(SendpayRoute)

ListchannelsRequest = _reflection.GeneratedProtocolMessageType('ListchannelsRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTCHANNELSREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListchannelsRequest)
  })
_sym_db.RegisterMessage(ListchannelsRequest)

ListchannelsResponse = _reflection.GeneratedProtocolMessageType('ListchannelsResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTCHANNELSRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListchannelsResponse)
  })
_sym_db.RegisterMessage(ListchannelsResponse)

ListchannelsChannels = _reflection.GeneratedProtocolMessageType('ListchannelsChannels', (_message.Message,), {
  'DESCRIPTOR' : _LISTCHANNELSCHANNELS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListchannelsChannels)
  })
_sym_db.RegisterMessage(ListchannelsChannels)

AddgossipRequest = _reflection.GeneratedProtocolMessageType('AddgossipRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDGOSSIPREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.AddgossipRequest)
  })
_sym_db.RegisterMessage(AddgossipRequest)

AddgossipResponse = _reflection.GeneratedProtocolMessageType('AddgossipResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDGOSSIPRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.AddgossipResponse)
  })
_sym_db.RegisterMessage(AddgossipResponse)

AutocleaninvoiceRequest = _reflection.GeneratedProtocolMessageType('AutocleaninvoiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUTOCLEANINVOICEREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.AutocleaninvoiceRequest)
  })
_sym_db.RegisterMessage(AutocleaninvoiceRequest)

AutocleaninvoiceResponse = _reflection.GeneratedProtocolMessageType('AutocleaninvoiceResponse', (_message.Message,), {
  'DESCRIPTOR' : _AUTOCLEANINVOICERESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.AutocleaninvoiceResponse)
  })
_sym_db.RegisterMessage(AutocleaninvoiceResponse)

CheckmessageRequest = _reflection.GeneratedProtocolMessageType('CheckmessageRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKMESSAGEREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.CheckmessageRequest)
  })
_sym_db.RegisterMessage(CheckmessageRequest)

CheckmessageResponse = _reflection.GeneratedProtocolMessageType('CheckmessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHECKMESSAGERESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.CheckmessageResponse)
  })
_sym_db.RegisterMessage(CheckmessageResponse)

CloseRequest = _reflection.GeneratedProtocolMessageType('CloseRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLOSEREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.CloseRequest)
  })
_sym_db.RegisterMessage(CloseRequest)

CloseResponse = _reflection.GeneratedProtocolMessageType('CloseResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLOSERESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.CloseResponse)
  })
_sym_db.RegisterMessage(CloseResponse)

ConnectRequest = _reflection.GeneratedProtocolMessageType('ConnectRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ConnectRequest)
  })
_sym_db.RegisterMessage(ConnectRequest)

ConnectResponse = _reflection.GeneratedProtocolMessageType('ConnectResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ConnectResponse)
  })
_sym_db.RegisterMessage(ConnectResponse)

ConnectAddress = _reflection.GeneratedProtocolMessageType('ConnectAddress', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTADDRESS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ConnectAddress)
  })
_sym_db.RegisterMessage(ConnectAddress)

CreateinvoiceRequest = _reflection.GeneratedProtocolMessageType('CreateinvoiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEINVOICEREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.CreateinvoiceRequest)
  })
_sym_db.RegisterMessage(CreateinvoiceRequest)

CreateinvoiceResponse = _reflection.GeneratedProtocolMessageType('CreateinvoiceResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEINVOICERESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.CreateinvoiceResponse)
  })
_sym_db.RegisterMessage(CreateinvoiceResponse)

DatastoreRequest = _reflection.GeneratedProtocolMessageType('DatastoreRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATASTOREREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.DatastoreRequest)
  })
_sym_db.RegisterMessage(DatastoreRequest)

DatastoreResponse = _reflection.GeneratedProtocolMessageType('DatastoreResponse', (_message.Message,), {
  'DESCRIPTOR' : _DATASTORERESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.DatastoreResponse)
  })
_sym_db.RegisterMessage(DatastoreResponse)

CreateonionRequest = _reflection.GeneratedProtocolMessageType('CreateonionRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEONIONREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.CreateonionRequest)
  })
_sym_db.RegisterMessage(CreateonionRequest)

CreateonionResponse = _reflection.GeneratedProtocolMessageType('CreateonionResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEONIONRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.CreateonionResponse)
  })
_sym_db.RegisterMessage(CreateonionResponse)

CreateonionHops = _reflection.GeneratedProtocolMessageType('CreateonionHops', (_message.Message,), {
  'DESCRIPTOR' : _CREATEONIONHOPS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.CreateonionHops)
  })
_sym_db.RegisterMessage(CreateonionHops)

DeldatastoreRequest = _reflection.GeneratedProtocolMessageType('DeldatastoreRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELDATASTOREREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.DeldatastoreRequest)
  })
_sym_db.RegisterMessage(DeldatastoreRequest)

DeldatastoreResponse = _reflection.GeneratedProtocolMessageType('DeldatastoreResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELDATASTORERESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.DeldatastoreResponse)
  })
_sym_db.RegisterMessage(DeldatastoreResponse)

DelexpiredinvoiceRequest = _reflection.GeneratedProtocolMessageType('DelexpiredinvoiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELEXPIREDINVOICEREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.DelexpiredinvoiceRequest)
  })
_sym_db.RegisterMessage(DelexpiredinvoiceRequest)

DelexpiredinvoiceResponse = _reflection.GeneratedProtocolMessageType('DelexpiredinvoiceResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELEXPIREDINVOICERESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.DelexpiredinvoiceResponse)
  })
_sym_db.RegisterMessage(DelexpiredinvoiceResponse)

DelinvoiceRequest = _reflection.GeneratedProtocolMessageType('DelinvoiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELINVOICEREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.DelinvoiceRequest)
  })
_sym_db.RegisterMessage(DelinvoiceRequest)

DelinvoiceResponse = _reflection.GeneratedProtocolMessageType('DelinvoiceResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELINVOICERESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.DelinvoiceResponse)
  })
_sym_db.RegisterMessage(DelinvoiceResponse)

InvoiceRequest = _reflection.GeneratedProtocolMessageType('InvoiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _INVOICEREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.InvoiceRequest)
  })
_sym_db.RegisterMessage(InvoiceRequest)

InvoiceResponse = _reflection.GeneratedProtocolMessageType('InvoiceResponse', (_message.Message,), {
  'DESCRIPTOR' : _INVOICERESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.InvoiceResponse)
  })
_sym_db.RegisterMessage(InvoiceResponse)

ListdatastoreRequest = _reflection.GeneratedProtocolMessageType('ListdatastoreRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTDATASTOREREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListdatastoreRequest)
  })
_sym_db.RegisterMessage(ListdatastoreRequest)

ListdatastoreResponse = _reflection.GeneratedProtocolMessageType('ListdatastoreResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTDATASTORERESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListdatastoreResponse)
  })
_sym_db.RegisterMessage(ListdatastoreResponse)

ListdatastoreDatastore = _reflection.GeneratedProtocolMessageType('ListdatastoreDatastore', (_message.Message,), {
  'DESCRIPTOR' : _LISTDATASTOREDATASTORE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListdatastoreDatastore)
  })
_sym_db.RegisterMessage(ListdatastoreDatastore)

ListinvoicesRequest = _reflection.GeneratedProtocolMessageType('ListinvoicesRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTINVOICESREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListinvoicesRequest)
  })
_sym_db.RegisterMessage(ListinvoicesRequest)

ListinvoicesResponse = _reflection.GeneratedProtocolMessageType('ListinvoicesResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTINVOICESRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListinvoicesResponse)
  })
_sym_db.RegisterMessage(ListinvoicesResponse)

ListinvoicesInvoices = _reflection.GeneratedProtocolMessageType('ListinvoicesInvoices', (_message.Message,), {
  'DESCRIPTOR' : _LISTINVOICESINVOICES,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListinvoicesInvoices)
  })
_sym_db.RegisterMessage(ListinvoicesInvoices)

SendonionRequest = _reflection.GeneratedProtocolMessageType('SendonionRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDONIONREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.SendonionRequest)
  })
_sym_db.RegisterMessage(SendonionRequest)

SendonionResponse = _reflection.GeneratedProtocolMessageType('SendonionResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDONIONRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.SendonionResponse)
  })
_sym_db.RegisterMessage(SendonionResponse)

SendonionFirst_hop = _reflection.GeneratedProtocolMessageType('SendonionFirst_hop', (_message.Message,), {
  'DESCRIPTOR' : _SENDONIONFIRST_HOP,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.SendonionFirst_hop)
  })
_sym_db.RegisterMessage(SendonionFirst_hop)

ListsendpaysRequest = _reflection.GeneratedProtocolMessageType('ListsendpaysRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTSENDPAYSREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListsendpaysRequest)
  })
_sym_db.RegisterMessage(ListsendpaysRequest)

ListsendpaysResponse = _reflection.GeneratedProtocolMessageType('ListsendpaysResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTSENDPAYSRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListsendpaysResponse)
  })
_sym_db.RegisterMessage(ListsendpaysResponse)

ListsendpaysPayments = _reflection.GeneratedProtocolMessageType('ListsendpaysPayments', (_message.Message,), {
  'DESCRIPTOR' : _LISTSENDPAYSPAYMENTS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListsendpaysPayments)
  })
_sym_db.RegisterMessage(ListsendpaysPayments)

ListtransactionsRequest = _reflection.GeneratedProtocolMessageType('ListtransactionsRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTTRANSACTIONSREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListtransactionsRequest)
  })
_sym_db.RegisterMessage(ListtransactionsRequest)

ListtransactionsResponse = _reflection.GeneratedProtocolMessageType('ListtransactionsResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTTRANSACTIONSRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListtransactionsResponse)
  })
_sym_db.RegisterMessage(ListtransactionsResponse)

ListtransactionsTransactions = _reflection.GeneratedProtocolMessageType('ListtransactionsTransactions', (_message.Message,), {
  'DESCRIPTOR' : _LISTTRANSACTIONSTRANSACTIONS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListtransactionsTransactions)
  })
_sym_db.RegisterMessage(ListtransactionsTransactions)

ListtransactionsTransactionsInputs = _reflection.GeneratedProtocolMessageType('ListtransactionsTransactionsInputs', (_message.Message,), {
  'DESCRIPTOR' : _LISTTRANSACTIONSTRANSACTIONSINPUTS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListtransactionsTransactionsInputs)
  })
_sym_db.RegisterMessage(ListtransactionsTransactionsInputs)

ListtransactionsTransactionsOutputs = _reflection.GeneratedProtocolMessageType('ListtransactionsTransactionsOutputs', (_message.Message,), {
  'DESCRIPTOR' : _LISTTRANSACTIONSTRANSACTIONSOUTPUTS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListtransactionsTransactionsOutputs)
  })
_sym_db.RegisterMessage(ListtransactionsTransactionsOutputs)

PayRequest = _reflection.GeneratedProtocolMessageType('PayRequest', (_message.Message,), {
  'DESCRIPTOR' : _PAYREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.PayRequest)
  })
_sym_db.RegisterMessage(PayRequest)

PayResponse = _reflection.GeneratedProtocolMessageType('PayResponse', (_message.Message,), {
  'DESCRIPTOR' : _PAYRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.PayResponse)
  })
_sym_db.RegisterMessage(PayResponse)

ListnodesRequest = _reflection.GeneratedProtocolMessageType('ListnodesRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTNODESREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListnodesRequest)
  })
_sym_db.RegisterMessage(ListnodesRequest)

ListnodesResponse = _reflection.GeneratedProtocolMessageType('ListnodesResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTNODESRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListnodesResponse)
  })
_sym_db.RegisterMessage(ListnodesResponse)

ListnodesNodes = _reflection.GeneratedProtocolMessageType('ListnodesNodes', (_message.Message,), {
  'DESCRIPTOR' : _LISTNODESNODES,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListnodesNodes)
  })
_sym_db.RegisterMessage(ListnodesNodes)

ListnodesNodesAddresses = _reflection.GeneratedProtocolMessageType('ListnodesNodesAddresses', (_message.Message,), {
  'DESCRIPTOR' : _LISTNODESNODESADDRESSES,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListnodesNodesAddresses)
  })
_sym_db.RegisterMessage(ListnodesNodesAddresses)

WaitanyinvoiceRequest = _reflection.GeneratedProtocolMessageType('WaitanyinvoiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _WAITANYINVOICEREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.WaitanyinvoiceRequest)
  })
_sym_db.RegisterMessage(WaitanyinvoiceRequest)

WaitanyinvoiceResponse = _reflection.GeneratedProtocolMessageType('WaitanyinvoiceResponse', (_message.Message,), {
  'DESCRIPTOR' : _WAITANYINVOICERESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.WaitanyinvoiceResponse)
  })
_sym_db.RegisterMessage(WaitanyinvoiceResponse)

WaitinvoiceRequest = _reflection.GeneratedProtocolMessageType('WaitinvoiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _WAITINVOICEREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.WaitinvoiceRequest)
  })
_sym_db.RegisterMessage(WaitinvoiceRequest)

WaitinvoiceResponse = _reflection.GeneratedProtocolMessageType('WaitinvoiceResponse', (_message.Message,), {
  'DESCRIPTOR' : _WAITINVOICERESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.WaitinvoiceResponse)
  })
_sym_db.RegisterMessage(WaitinvoiceResponse)

WaitsendpayRequest = _reflection.GeneratedProtocolMessageType('WaitsendpayRequest', (_message.Message,), {
  'DESCRIPTOR' : _WAITSENDPAYREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.WaitsendpayRequest)
  })
_sym_db.RegisterMessage(WaitsendpayRequest)

WaitsendpayResponse = _reflection.GeneratedProtocolMessageType('WaitsendpayResponse', (_message.Message,), {
  'DESCRIPTOR' : _WAITSENDPAYRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.WaitsendpayResponse)
  })
_sym_db.RegisterMessage(WaitsendpayResponse)

NewaddrRequest = _reflection.GeneratedProtocolMessageType('NewaddrRequest', (_message.Message,), {
  'DESCRIPTOR' : _NEWADDRREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.NewaddrRequest)
  })
_sym_db.RegisterMessage(NewaddrRequest)

NewaddrResponse = _reflection.GeneratedProtocolMessageType('NewaddrResponse', (_message.Message,), {
  'DESCRIPTOR' : _NEWADDRRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.NewaddrResponse)
  })
_sym_db.RegisterMessage(NewaddrResponse)

WithdrawRequest = _reflection.GeneratedProtocolMessageType('WithdrawRequest', (_message.Message,), {
  'DESCRIPTOR' : _WITHDRAWREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.WithdrawRequest)
  })
_sym_db.RegisterMessage(WithdrawRequest)

WithdrawResponse = _reflection.GeneratedProtocolMessageType('WithdrawResponse', (_message.Message,), {
  'DESCRIPTOR' : _WITHDRAWRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.WithdrawResponse)
  })
_sym_db.RegisterMessage(WithdrawResponse)

KeysendRequest = _reflection.GeneratedProtocolMessageType('KeysendRequest', (_message.Message,), {
  'DESCRIPTOR' : _KEYSENDREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.KeysendRequest)
  })
_sym_db.RegisterMessage(KeysendRequest)

KeysendResponse = _reflection.GeneratedProtocolMessageType('KeysendResponse', (_message.Message,), {
  'DESCRIPTOR' : _KEYSENDRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.KeysendResponse)
  })
_sym_db.RegisterMessage(KeysendResponse)

KeysendExtratlvs = _reflection.GeneratedProtocolMessageType('KeysendExtratlvs', (_message.Message,), {
  'DESCRIPTOR' : _KEYSENDEXTRATLVS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.KeysendExtratlvs)
  })
_sym_db.RegisterMessage(KeysendExtratlvs)

FundpsbtRequest = _reflection.GeneratedProtocolMessageType('FundpsbtRequest', (_message.Message,), {
  'DESCRIPTOR' : _FUNDPSBTREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.FundpsbtRequest)
  })
_sym_db.RegisterMessage(FundpsbtRequest)

FundpsbtResponse = _reflection.GeneratedProtocolMessageType('FundpsbtResponse', (_message.Message,), {
  'DESCRIPTOR' : _FUNDPSBTRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.FundpsbtResponse)
  })
_sym_db.RegisterMessage(FundpsbtResponse)

FundpsbtReservations = _reflection.GeneratedProtocolMessageType('FundpsbtReservations', (_message.Message,), {
  'DESCRIPTOR' : _FUNDPSBTRESERVATIONS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.FundpsbtReservations)
  })
_sym_db.RegisterMessage(FundpsbtReservations)

SendpsbtRequest = _reflection.GeneratedProtocolMessageType('SendpsbtRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDPSBTREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.SendpsbtRequest)
  })
_sym_db.RegisterMessage(SendpsbtRequest)

SendpsbtResponse = _reflection.GeneratedProtocolMessageType('SendpsbtResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDPSBTRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.SendpsbtResponse)
  })
_sym_db.RegisterMessage(SendpsbtResponse)

SignpsbtRequest = _reflection.GeneratedProtocolMessageType('SignpsbtRequest', (_message.Message,), {
  'DESCRIPTOR' : _SIGNPSBTREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.SignpsbtRequest)
  })
_sym_db.RegisterMessage(SignpsbtRequest)

SignpsbtResponse = _reflection.GeneratedProtocolMessageType('SignpsbtResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIGNPSBTRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.SignpsbtResponse)
  })
_sym_db.RegisterMessage(SignpsbtResponse)

UtxopsbtRequest = _reflection.GeneratedProtocolMessageType('UtxopsbtRequest', (_message.Message,), {
  'DESCRIPTOR' : _UTXOPSBTREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.UtxopsbtRequest)
  })
_sym_db.RegisterMessage(UtxopsbtRequest)

UtxopsbtResponse = _reflection.GeneratedProtocolMessageType('UtxopsbtResponse', (_message.Message,), {
  'DESCRIPTOR' : _UTXOPSBTRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.UtxopsbtResponse)
  })
_sym_db.RegisterMessage(UtxopsbtResponse)

UtxopsbtReservations = _reflection.GeneratedProtocolMessageType('UtxopsbtReservations', (_message.Message,), {
  'DESCRIPTOR' : _UTXOPSBTRESERVATIONS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.UtxopsbtReservations)
  })
_sym_db.RegisterMessage(UtxopsbtReservations)

TxdiscardRequest = _reflection.GeneratedProtocolMessageType('TxdiscardRequest', (_message.Message,), {
  'DESCRIPTOR' : _TXDISCARDREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.TxdiscardRequest)
  })
_sym_db.RegisterMessage(TxdiscardRequest)

TxdiscardResponse = _reflection.GeneratedProtocolMessageType('TxdiscardResponse', (_message.Message,), {
  'DESCRIPTOR' : _TXDISCARDRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.TxdiscardResponse)
  })
_sym_db.RegisterMessage(TxdiscardResponse)

TxprepareRequest = _reflection.GeneratedProtocolMessageType('TxprepareRequest', (_message.Message,), {
  'DESCRIPTOR' : _TXPREPAREREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.TxprepareRequest)
  })
_sym_db.RegisterMessage(TxprepareRequest)

TxprepareResponse = _reflection.GeneratedProtocolMessageType('TxprepareResponse', (_message.Message,), {
  'DESCRIPTOR' : _TXPREPARERESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.TxprepareResponse)
  })
_sym_db.RegisterMessage(TxprepareResponse)

TxsendRequest = _reflection.GeneratedProtocolMessageType('TxsendRequest', (_message.Message,), {
  'DESCRIPTOR' : _TXSENDREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.TxsendRequest)
  })
_sym_db.RegisterMessage(TxsendRequest)

TxsendResponse = _reflection.GeneratedProtocolMessageType('TxsendResponse', (_message.Message,), {
  'DESCRIPTOR' : _TXSENDRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.TxsendResponse)
  })
_sym_db.RegisterMessage(TxsendResponse)

DisconnectRequest = _reflection.GeneratedProtocolMessageType('DisconnectRequest', (_message.Message,), {
  'DESCRIPTOR' : _DISCONNECTREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.DisconnectRequest)
  })
_sym_db.RegisterMessage(DisconnectRequest)

DisconnectResponse = _reflection.GeneratedProtocolMessageType('DisconnectResponse', (_message.Message,), {
  'DESCRIPTOR' : _DISCONNECTRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.DisconnectResponse)
  })
_sym_db.RegisterMessage(DisconnectResponse)

FeeratesRequest = _reflection.GeneratedProtocolMessageType('FeeratesRequest', (_message.Message,), {
  'DESCRIPTOR' : _FEERATESREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.FeeratesRequest)
  })
_sym_db.RegisterMessage(FeeratesRequest)

FeeratesResponse = _reflection.GeneratedProtocolMessageType('FeeratesResponse', (_message.Message,), {
  'DESCRIPTOR' : _FEERATESRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.FeeratesResponse)
  })
_sym_db.RegisterMessage(FeeratesResponse)

FeeratesPerkb = _reflection.GeneratedProtocolMessageType('FeeratesPerkb', (_message.Message,), {
  'DESCRIPTOR' : _FEERATESPERKB,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.FeeratesPerkb)
  })
_sym_db.RegisterMessage(FeeratesPerkb)

FeeratesPerkw = _reflection.GeneratedProtocolMessageType('FeeratesPerkw', (_message.Message,), {
  'DESCRIPTOR' : _FEERATESPERKW,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.FeeratesPerkw)
  })
_sym_db.RegisterMessage(FeeratesPerkw)

FeeratesOnchain_fee_estimates = _reflection.GeneratedProtocolMessageType('FeeratesOnchain_fee_estimates', (_message.Message,), {
  'DESCRIPTOR' : _FEERATESONCHAIN_FEE_ESTIMATES,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.FeeratesOnchain_fee_estimates)
  })
_sym_db.RegisterMessage(FeeratesOnchain_fee_estimates)

FundchannelRequest = _reflection.GeneratedProtocolMessageType('FundchannelRequest', (_message.Message,), {
  'DESCRIPTOR' : _FUNDCHANNELREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.FundchannelRequest)
  })
_sym_db.RegisterMessage(FundchannelRequest)

FundchannelResponse = _reflection.GeneratedProtocolMessageType('FundchannelResponse', (_message.Message,), {
  'DESCRIPTOR' : _FUNDCHANNELRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.FundchannelResponse)
  })
_sym_db.RegisterMessage(FundchannelResponse)

GetrouteRequest = _reflection.GeneratedProtocolMessageType('GetrouteRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETROUTEREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.GetrouteRequest)
  })
_sym_db.RegisterMessage(GetrouteRequest)

GetrouteResponse = _reflection.GeneratedProtocolMessageType('GetrouteResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETROUTERESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.GetrouteResponse)
  })
_sym_db.RegisterMessage(GetrouteResponse)

GetrouteRoute = _reflection.GeneratedProtocolMessageType('GetrouteRoute', (_message.Message,), {
  'DESCRIPTOR' : _GETROUTEROUTE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.GetrouteRoute)
  })
_sym_db.RegisterMessage(GetrouteRoute)

ListforwardsRequest = _reflection.GeneratedProtocolMessageType('ListforwardsRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTFORWARDSREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListforwardsRequest)
  })
_sym_db.RegisterMessage(ListforwardsRequest)

ListforwardsResponse = _reflection.GeneratedProtocolMessageType('ListforwardsResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTFORWARDSRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListforwardsResponse)
  })
_sym_db.RegisterMessage(ListforwardsResponse)

ListforwardsForwards = _reflection.GeneratedProtocolMessageType('ListforwardsForwards', (_message.Message,), {
  'DESCRIPTOR' : _LISTFORWARDSFORWARDS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListforwardsForwards)
  })
_sym_db.RegisterMessage(ListforwardsForwards)

ListpaysRequest = _reflection.GeneratedProtocolMessageType('ListpaysRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTPAYSREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListpaysRequest)
  })
_sym_db.RegisterMessage(ListpaysRequest)

ListpaysResponse = _reflection.GeneratedProtocolMessageType('ListpaysResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTPAYSRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListpaysResponse)
  })
_sym_db.RegisterMessage(ListpaysResponse)

ListpaysPays = _reflection.GeneratedProtocolMessageType('ListpaysPays', (_message.Message,), {
  'DESCRIPTOR' : _LISTPAYSPAYS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.ListpaysPays)
  })
_sym_db.RegisterMessage(ListpaysPays)

PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), {
  'DESCRIPTOR' : _PINGREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.PingRequest)
  })
_sym_db.RegisterMessage(PingRequest)

PingResponse = _reflection.GeneratedProtocolMessageType('PingResponse', (_message.Message,), {
  'DESCRIPTOR' : _PINGRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.PingResponse)
  })
_sym_db.RegisterMessage(PingResponse)

SignmessageRequest = _reflection.GeneratedProtocolMessageType('SignmessageRequest', (_message.Message,), {
  'DESCRIPTOR' : _SIGNMESSAGEREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.SignmessageRequest)
  })
_sym_db.RegisterMessage(SignmessageRequest)

SignmessageResponse = _reflection.GeneratedProtocolMessageType('SignmessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIGNMESSAGERESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.SignmessageResponse)
  })
_sym_db.RegisterMessage(SignmessageResponse)

StopRequest = _reflection.GeneratedProtocolMessageType('StopRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOPREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.StopRequest)
  })
_sym_db.RegisterMessage(StopRequest)

StopResponse = _reflection.GeneratedProtocolMessageType('StopResponse', (_message.Message,), {
  'DESCRIPTOR' : _STOPRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:cln.StopResponse)
  })
_sym_db.RegisterMessage(StopResponse)

_NODE = DESCRIPTOR.services_by_name['Node']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETINFOREQUEST._serialized_start=37
  _GETINFOREQUEST._serialized_end=53
  _GETINFORESPONSE._serialized_start=56
  _GETINFORESPONSE._serialized_end=548
  _GETINFOOUR_FEATURES._serialized_start=550
  _GETINFOOUR_FEATURES._serialized_end=633
  _GETINFOADDRESS._serialized_start=636
  _GETINFOADDRESS._serialized_end=847
  _GETINFOADDRESS_GETINFOADDRESSTYPE._serialized_start=749
  _GETINFOADDRESS_GETINFOADDRESSTYPE._serialized_end=835
  _GETINFOBINDING._serialized_start=850
  _GETINFOBINDING._serialized_end=1101
  _GETINFOBINDING_GETINFOBINDINGTYPE._serialized_start=989
  _GETINFOBINDING_GETINFOBINDINGTYPE._serialized_end=1069
  _LISTPEERSREQUEST._serialized_start=1103
  _LISTPEERSREQUEST._serialized_end=1175
  _LISTPEERSRESPONSE._serialized_start=1177
  _LISTPEERSRESPONSE._serialized_end=1232
  _LISTPEERSPEERS._serialized_start=1235
<<<<<<< HEAD
  _LISTPEERSPEERS._serialized_end=1461
  _LISTPEERSPEERSLOG._serialized_start=1464
  _LISTPEERSPEERSLOG._serialized_end=1845
  _LISTPEERSPEERSLOG_LISTPEERSPEERSLOGTYPE._serialized_start=1675
  _LISTPEERSPEERSLOG_LISTPEERSPEERSLOGTYPE._serialized_end=1780
  _LISTPEERSPEERSCHANNELS._serialized_start=1848
  _LISTPEERSPEERSCHANNELS._serialized_end=4674
  _LISTPEERSPEERSCHANNELS_LISTPEERSPEERSCHANNELSSTATE._serialized_start=3578
  _LISTPEERSPEERSCHANNELS_LISTPEERSPEERSCHANNELSSTATE._serialized_end=3867
  _LISTPEERSPEERSCHANNELSFEERATE._serialized_start=4676
  _LISTPEERSPEERSCHANNELSFEERATE._serialized_end=4737
  _LISTPEERSPEERSCHANNELSINFLIGHT._serialized_start=4740
  _LISTPEERSPEERSCHANNELSINFLIGHT._serialized_end=4937
  _LISTPEERSPEERSCHANNELSFUNDING._serialized_start=4940
  _LISTPEERSPEERSCHANNELSFUNDING._serialized_end=5331
  _LISTPEERSPEERSCHANNELSALIAS._serialized_start=5333
  _LISTPEERSPEERSCHANNELSALIAS._serialized_end=5424
  _LISTPEERSPEERSCHANNELSHTLCS._serialized_start=5427
  _LISTPEERSPEERSCHANNELSHTLCS._serialized_end=5765
  _LISTPEERSPEERSCHANNELSHTLCS_LISTPEERSPEERSCHANNELSHTLCSDIRECTION._serialized_start=5681
  _LISTPEERSPEERSCHANNELSHTLCS_LISTPEERSPEERSCHANNELSHTLCSDIRECTION._serialized_end=5736
  _LISTFUNDSREQUEST._serialized_start=5767
  _LISTFUNDSREQUEST._serialized_end=5815
  _LISTFUNDSRESPONSE._serialized_start=5817
  _LISTFUNDSRESPONSE._serialized_end=5918
  _LISTFUNDSOUTPUTS._serialized_start=5921
  _LISTFUNDSOUTPUTS._serialized_end=6294
  _LISTFUNDSOUTPUTS_LISTFUNDSOUTPUTSSTATUS._serialized_start=6182
  _LISTFUNDSOUTPUTS_LISTFUNDSOUTPUTSSTATUS._serialized_end=6249
  _LISTFUNDSCHANNELS._serialized_start=6297
  _LISTFUNDSCHANNELS._serialized_end=6556
  _SENDPAYREQUEST._serialized_start=6559
  _SENDPAYREQUEST._serialized_end=6906
  _SENDPAYRESPONSE._serialized_start=6909
  _SENDPAYRESPONSE._serialized_end=7502
  _SENDPAYRESPONSE_SENDPAYSTATUS._serialized_start=7323
  _SENDPAYRESPONSE_SENDPAYSTATUS._serialized_end=7365
  _SENDPAYROUTE._serialized_start=7504
  _SENDPAYROUTE._serialized_end=7596
  _LISTCHANNELSREQUEST._serialized_start=7599
  _LISTCHANNELSREQUEST._serialized_end=7746
  _LISTCHANNELSRESPONSE._serialized_start=7748
  _LISTCHANNELSRESPONSE._serialized_end=7815
  _LISTCHANNELSCHANNELS._serialized_start=7818
  _LISTCHANNELSCHANNELS._serialized_end=8234
  _ADDGOSSIPREQUEST._serialized_start=8236
  _ADDGOSSIPREQUEST._serialized_end=8271
  _ADDGOSSIPRESPONSE._serialized_start=8273
  _ADDGOSSIPRESPONSE._serialized_end=8292
  _AUTOCLEANINVOICEREQUEST._serialized_start=8294
  _AUTOCLEANINVOICEREQUEST._serialized_end=8405
  _AUTOCLEANINVOICERESPONSE._serialized_start=8408
  _AUTOCLEANINVOICERESPONSE._serialized_end=8537
  _CHECKMESSAGEREQUEST._serialized_start=8539
  _CHECKMESSAGEREQUEST._serialized_end=8624
  _CHECKMESSAGERESPONSE._serialized_start=8626
  _CHECKMESSAGERESPONSE._serialized_end=8682
  _CLOSEREQUEST._serialized_start=8685
  _CLOSEREQUEST._serialized_end=9001
  _CLOSERESPONSE._serialized_start=9004
  _CLOSERESPONSE._serialized_end=9175
  _CLOSERESPONSE_CLOSETYPE._serialized_start=9106
  _CLOSERESPONSE_CLOSETYPE._serialized_end=9159
  _CONNECTREQUEST._serialized_start=9177
  _CONNECTREQUEST._serialized_end=9261
  _CONNECTRESPONSE._serialized_start=9264
  _CONNECTRESPONSE._serialized_end=9406
  _CONNECTRESPONSE_CONNECTDIRECTION._serialized_start=9371
  _CONNECTRESPONSE_CONNECTDIRECTION._serialized_end=9406
  _CONNECTADDRESS._serialized_start=9409
  _CONNECTADDRESS._serialized_end=9660
  _CONNECTADDRESS_CONNECTADDRESSTYPE._serialized_start=9548
  _CONNECTADDRESS_CONNECTADDRESSTYPE._serialized_end=9628
  _CREATEINVOICEREQUEST._serialized_start=9662
  _CREATEINVOICEREQUEST._serialized_end=9736
  _CREATEINVOICERESPONSE._serialized_start=9739
  _CREATEINVOICERESPONSE._serialized_end=10366
  _CREATEINVOICERESPONSE_CREATEINVOICESTATUS._serialized_start=10166
  _CREATEINVOICERESPONSE_CREATEINVOICESTATUS._serialized_end=10222
  _DATASTOREREQUEST._serialized_start=10369
  _DATASTOREREQUEST._serialized_end=10677
  _DATASTOREREQUEST_DATASTOREMODE._serialized_start=10522
  _DATASTOREREQUEST_DATASTOREMODE._serialized_end=10634
  _DATASTORERESPONSE._serialized_start=10680
  _DATASTORERESPONSE._serialized_end=10810
  _CREATEONIONREQUEST._serialized_start=10813
  _CREATEONIONREQUEST._serialized_end=10970
  _CREATEONIONRESPONSE._serialized_start=10972
  _CREATEONIONRESPONSE._serialized_end=11032
  _CREATEONIONHOPS._serialized_start=11034
  _CREATEONIONHOPS._serialized_end=11084
  _DELDATASTOREREQUEST._serialized_start=11086
  _DELDATASTOREREQUEST._serialized_end=11160
  _DELDATASTORERESPONSE._serialized_start=11163
  _DELDATASTORERESPONSE._serialized_end=11296
  _DELEXPIREDINVOICEREQUEST._serialized_start=11298
  _DELEXPIREDINVOICEREQUEST._serialized_end=11370
  _DELEXPIREDINVOICERESPONSE._serialized_start=11372
  _DELEXPIREDINVOICERESPONSE._serialized_end=11399
  _DELINVOICEREQUEST._serialized_start=11402
  _DELINVOICEREQUEST._serialized_end=11584
  _DELINVOICEREQUEST_DELINVOICESTATUS._serialized_start=11518
  _DELINVOICEREQUEST_DELINVOICESTATUS._serialized_end=11571
  _DELINVOICERESPONSE._serialized_start=11587
  _DELINVOICERESPONSE._serialized_end=12026
  _DELINVOICERESPONSE_DELINVOICESTATUS._serialized_start=11518
  _DELINVOICERESPONSE_DELINVOICESTATUS._serialized_end=11571
  _INVOICEREQUEST._serialized_start=12029
  _INVOICEREQUEST._serialized_end=12341
  _INVOICERESPONSE._serialized_start=12344
  _INVOICERESPONSE._serialized_end=12703
  _LISTDATASTOREREQUEST._serialized_start=12705
  _LISTDATASTOREREQUEST._serialized_end=12740
  _LISTDATASTORERESPONSE._serialized_start=12742
  _LISTDATASTORERESPONSE._serialized_end=12813
  _LISTDATASTOREDATASTORE._serialized_start=12816
  _LISTDATASTOREDATASTORE._serialized_end=12951
  _LISTINVOICESREQUEST._serialized_start=12954
  _LISTINVOICESREQUEST._serialized_end=13123
  _LISTINVOICESRESPONSE._serialized_start=13125
  _LISTINVOICESRESPONSE._serialized_end=13192
  _LISTINVOICESINVOICES._serialized_start=13195
  _LISTINVOICESINVOICES._serialized_end=13855
  _LISTINVOICESINVOICES_LISTINVOICESINVOICESSTATUS._serialized_start=13632
  _LISTINVOICESINVOICES_LISTINVOICESINVOICESSTATUS._serialized_end=13695
  _SENDONIONREQUEST._serialized_start=13858
  _SENDONIONREQUEST._serialized_end=14206
  _SENDONIONRESPONSE._serialized_start=14209
  _SENDONIONRESPONSE._serialized_end=14732
  _SENDONIONRESPONSE_SENDONIONSTATUS._serialized_start=14580
  _SENDONIONRESPONSE_SENDONIONSTATUS._serialized_end=14624
  _SENDONIONFIRST_HOP._serialized_start=14734
  _SENDONIONFIRST_HOP._serialized_end=14815
  _LISTSENDPAYSREQUEST._serialized_start=14818
  _LISTSENDPAYSREQUEST._serialized_end=15053
  _LISTSENDPAYSREQUEST_LISTSENDPAYSSTATUS._serialized_start=14955
  _LISTSENDPAYSREQUEST_LISTSENDPAYSSTATUS._serialized_end=15014
  _LISTSENDPAYSRESPONSE._serialized_start=15055
  _LISTSENDPAYSRESPONSE._serialized_end=15122
  _LISTSENDPAYSPAYMENTS._serialized_start=15125
  _LISTSENDPAYSPAYMENTS._serialized_end=15738
  _LISTSENDPAYSPAYMENTS_LISTSENDPAYSPAYMENTSSTATUS._serialized_start=15543
  _LISTSENDPAYSPAYMENTS_LISTSENDPAYSPAYMENTSSTATUS._serialized_end=15610
  _LISTTRANSACTIONSREQUEST._serialized_start=15740
  _LISTTRANSACTIONSREQUEST._serialized_end=15765
  _LISTTRANSACTIONSRESPONSE._serialized_start=15767
  _LISTTRANSACTIONSRESPONSE._serialized_end=15850
  _LISTTRANSACTIONSTRANSACTIONS._serialized_start=15853
  _LISTTRANSACTIONSTRANSACTIONS._serialized_end=16135
  _LISTTRANSACTIONSTRANSACTIONSINPUTS._serialized_start=16138
  _LISTTRANSACTIONSTRANSACTIONSINPUTS._serialized_end=16654
  _LISTTRANSACTIONSTRANSACTIONSINPUTS_LISTTRANSACTIONSTRANSACTIONSINPUTSTYPE._serialized_start=16350
  _LISTTRANSACTIONSTRANSACTIONSINPUTS_LISTTRANSACTIONSTRANSACTIONSINPUTSTYPE._serialized_end=16628
  _LISTTRANSACTIONSTRANSACTIONSOUTPUTS._serialized_start=16657
  _LISTTRANSACTIONSTRANSACTIONSOUTPUTS._serialized_end=17201
  _LISTTRANSACTIONSTRANSACTIONSOUTPUTS_LISTTRANSACTIONSTRANSACTIONSOUTPUTSTYPE._serialized_start=16896
  _LISTTRANSACTIONSTRANSACTIONSOUTPUTS_LISTTRANSACTIONSTRANSACTIONSOUTPUTSTYPE._serialized_end=17175
  _PAYREQUEST._serialized_start=17204
  _PAYREQUEST._serialized_end=17676
  _PAYRESPONSE._serialized_start=17679
  _PAYRESPONSE._serialized_end=18058
  _PAYRESPONSE_PAYSTATUS._serialized_start=17961
  _PAYRESPONSE_PAYSTATUS._serialized_end=18011
  _LISTNODESREQUEST._serialized_start=18060
  _LISTNODESREQUEST._serialized_end=18102
  _LISTNODESRESPONSE._serialized_start=18104
  _LISTNODESRESPONSE._serialized_end=18159
  _LISTNODESNODES._serialized_start=18162
  _LISTNODESNODES._serialized_end=18387
  _LISTNODESNODESADDRESSES._serialized_start=18390
  _LISTNODESNODESADDRESSES._serialized_end=18637
  _LISTNODESNODESADDRESSES_LISTNODESNODESADDRESSESTYPE._serialized_start=18530
  _LISTNODESNODESADDRESSES_LISTNODESNODESADDRESSESTYPE._serialized_end=18625
  _WAITANYINVOICEREQUEST._serialized_start=18639
  _WAITANYINVOICEREQUEST._serialized_end=18742
  _WAITANYINVOICERESPONSE._serialized_start=18745
  _WAITANYINVOICERESPONSE._serialized_end=19276
  _WAITANYINVOICERESPONSE_WAITANYINVOICESTATUS._serialized_start=19121
  _WAITANYINVOICERESPONSE_WAITANYINVOICESTATUS._serialized_end=19166
  _WAITINVOICEREQUEST._serialized_start=19278
  _WAITINVOICEREQUEST._serialized_end=19313
  _WAITINVOICERESPONSE._serialized_start=19316
  _WAITINVOICERESPONSE._serialized_end=19835
  _WAITINVOICERESPONSE_WAITINVOICESTATUS._serialized_start=19683
  _WAITINVOICERESPONSE_WAITINVOICESTATUS._serialized_end=19725
  _WAITSENDPAYREQUEST._serialized_start=19838
  _WAITSENDPAYREQUEST._serialized_end=19980
  _WAITSENDPAYRESPONSE._serialized_start=19983
  _WAITSENDPAYRESPONSE._serialized_end=20545
  _WAITSENDPAYRESPONSE_WAITSENDPAYSTATUS._serialized_start=20387
  _WAITSENDPAYRESPONSE_WAITSENDPAYSTATUS._serialized_end=20420
  _NEWADDRREQUEST._serialized_start=20548
  _NEWADDRREQUEST._serialized_end=20706
  _NEWADDRREQUEST_NEWADDRADDRESSTYPE._serialized_start=20632
  _NEWADDRREQUEST_NEWADDRADDRESSTYPE._serialized_end=20690
  _NEWADDRRESPONSE._serialized_start=20708
  _NEWADDRRESPONSE._serialized_end=20799
  _WITHDRAWREQUEST._serialized_start=20802
  _WITHDRAWREQUEST._serialized_end=21004
  _WITHDRAWRESPONSE._serialized_start=21006
  _WITHDRAWRESPONSE._serialized_end=21064
  _KEYSENDREQUEST._serialized_start=21067
  _KEYSENDREQUEST._serialized_end=21399
  _KEYSENDRESPONSE._serialized_start=21402
  _KEYSENDRESPONSE._serialized_end=21772
  _KEYSENDRESPONSE_KEYSENDSTATUS._serialized_start=21696
  _KEYSENDRESPONSE_KEYSENDSTATUS._serialized_end=21725
  _KEYSENDEXTRATLVS._serialized_start=21774
  _KEYSENDEXTRATLVS._serialized_end=21792
  _FUNDPSBTREQUEST._serialized_start=21795
  _FUNDPSBTREQUEST._serialized_end=22106
  _FUNDPSBTRESPONSE._serialized_start=22109
  _FUNDPSBTRESPONSE._serialized_end=22326
  _FUNDPSBTRESERVATIONS._serialized_start=22328
  _FUNDPSBTRESERVATIONS._serialized_end=22445
  _SENDPSBTREQUEST._serialized_start=22447
  _SENDPSBTREQUEST._serialized_end=22512
  _SENDPSBTRESPONSE._serialized_start=22514
  _SENDPSBTRESPONSE._serialized_end=22558
  _SIGNPSBTREQUEST._serialized_start=22560
  _SIGNPSBTREQUEST._serialized_end=22609
  _SIGNPSBTRESPONSE._serialized_start=22611
  _SIGNPSBTRESPONSE._serialized_end=22650
  _UTXOPSBTREQUEST._serialized_start=22653
  _UTXOPSBTREQUEST._serialized_end=23000
  _UTXOPSBTRESPONSE._serialized_start=23003
  _UTXOPSBTRESPONSE._serialized_end=23220
  _UTXOPSBTRESERVATIONS._serialized_start=23222
  _UTXOPSBTRESERVATIONS._serialized_end=23339
  _TXDISCARDREQUEST._serialized_start=23341
  _TXDISCARDREQUEST._serialized_end=23373
  _TXDISCARDRESPONSE._serialized_start=23375
  _TXDISCARDRESPONSE._serialized_end=23429
  _TXPREPAREREQUEST._serialized_start=23432
  _TXPREPAREREQUEST._serialized_end=23596
  _TXPREPARERESPONSE._serialized_start=23598
  _TXPREPARERESPONSE._serialized_end=23666
  _TXSENDREQUEST._serialized_start=23668
  _TXSENDREQUEST._serialized_end=23697
  _TXSENDRESPONSE._serialized_start=23699
  _TXSENDRESPONSE._serialized_end=23755
  _DISCONNECTREQUEST._serialized_start=23757
  _DISCONNECTREQUEST._serialized_end=23818
  _DISCONNECTRESPONSE._serialized_start=23820
  _DISCONNECTRESPONSE._serialized_end=23840
  _FEERATESREQUEST._serialized_start=23842
  _FEERATESREQUEST._serialized_end=23949
  _FEERATESREQUEST_FEERATESSTYLE._serialized_start=23912
  _FEERATESREQUEST_FEERATESSTYLE._serialized_end=23949
  _FEERATESRESPONSE._serialized_start=23951
  _FEERATESRESPONSE._serialized_end=24037
  _FEERATESPERKB._serialized_start=24040
  _FEERATESPERKB._serialized_end=24363
  _FEERATESPERKW._serialized_start=24366
  _FEERATESPERKW._serialized_end=24689
  _FEERATESONCHAIN_FEE_ESTIMATES._serialized_start=24692
  _FEERATESONCHAIN_FEE_ESTIMATES._serialized_end=24885
  _FUNDCHANNELREQUEST._serialized_start=24888
  _FUNDCHANNELREQUEST._serialized_end=25326
  _FUNDCHANNELRESPONSE._serialized_start=25329
  _FUNDCHANNELRESPONSE._serialized_end=25484
  _GETROUTEREQUEST._serialized_start=25487
  _GETROUTEREQUEST._serialized_end=25723
  _GETROUTERESPONSE._serialized_start=25725
  _GETROUTERESPONSE._serialized_end=25778
  _GETROUTEROUTE._serialized_start=25781
  _GETROUTEROUTE._serialized_end=25978
  _GETROUTEROUTE_GETROUTEROUTESTYLE._serialized_start=25949
  _GETROUTEROUTE_GETROUTEROUTESTYLE._serialized_end=25978
  _LISTFORWARDSREQUEST._serialized_start=25981
  _LISTFORWARDSREQUEST._serialized_end=26239
  _LISTFORWARDSREQUEST_LISTFORWARDSSTATUS._serialized_start=26121
  _LISTFORWARDSREQUEST_LISTFORWARDSSTATUS._serialized_end=26197
  _LISTFORWARDSRESPONSE._serialized_start=26241
  _LISTFORWARDSRESPONSE._serialized_end=26308
  _LISTFORWARDSFORWARDS._serialized_start=26311
  _LISTFORWARDSFORWARDS._serialized_end=26879
  _LISTFORWARDSFORWARDS_LISTFORWARDSFORWARDSSTATUS._serialized_start=26676
  _LISTFORWARDSFORWARDS_LISTFORWARDSFORWARDSSTATUS._serialized_end=26760
  _LISTFORWARDSFORWARDS_LISTFORWARDSFORWARDSSTYLE._serialized_start=26762
  _LISTFORWARDSFORWARDS_LISTFORWARDSFORWARDSSTYLE._serialized_end=26810
  _LISTPAYSREQUEST._serialized_start=26882
  _LISTPAYSREQUEST._serialized_end=27101
  _LISTPAYSREQUEST_LISTPAYSSTATUS._serialized_start=27007
  _LISTPAYSREQUEST_LISTPAYSSTATUS._serialized_end=27062
  _LISTPAYSRESPONSE._serialized_start=27103
  _LISTPAYSRESPONSE._serialized_end=27154
  _LISTPAYSPAYS._serialized_start=27157
  _LISTPAYSPAYS._serialized_end=27676
  _LISTPAYSPAYS_LISTPAYSPAYSSTATUS._serialized_start=27488
  _LISTPAYSPAYS_LISTPAYSPAYSSTATUS._serialized_end=27547
  _PINGREQUEST._serialized_start=27678
  _PINGREQUEST._serialized_end=27767
  _PINGRESPONSE._serialized_start=27769
  _PINGRESPONSE._serialized_end=27799
  _SIGNMESSAGEREQUEST._serialized_start=27801
  _SIGNMESSAGEREQUEST._serialized_end=27838
  _SIGNMESSAGERESPONSE._serialized_start=27840
  _SIGNMESSAGERESPONSE._serialized_end=27910
  _STOPREQUEST._serialized_start=27912
  _STOPREQUEST._serialized_end=27925
  _STOPRESPONSE._serialized_start=27927
  _STOPRESPONSE._serialized_end=27941
  _NODE._serialized_start=27944
  _NODE._serialized_end=30872
=======
  _LISTPEERSPEERS._serialized_end=1414
  _LISTPEERSPEERSLOG._serialized_start=1417
  _LISTPEERSPEERSLOG._serialized_end=1798
  _LISTPEERSPEERSLOG_LISTPEERSPEERSLOGTYPE._serialized_start=1628
  _LISTPEERSPEERSLOG_LISTPEERSPEERSLOGTYPE._serialized_end=1733
  _LISTFUNDSREQUEST._serialized_start=1800
  _LISTFUNDSREQUEST._serialized_end=1848
  _LISTFUNDSRESPONSE._serialized_start=1850
  _LISTFUNDSRESPONSE._serialized_end=1951
  _LISTFUNDSOUTPUTS._serialized_start=1954
  _LISTFUNDSOUTPUTS._serialized_end=2327
  _LISTFUNDSOUTPUTS_LISTFUNDSOUTPUTSSTATUS._serialized_start=2215
  _LISTFUNDSOUTPUTS_LISTFUNDSOUTPUTSSTATUS._serialized_end=2282
  _LISTFUNDSCHANNELS._serialized_start=2330
  _LISTFUNDSCHANNELS._serialized_end=2589
  _SENDPAYREQUEST._serialized_start=2592
  _SENDPAYREQUEST._serialized_end=2939
  _SENDPAYRESPONSE._serialized_start=2942
  _SENDPAYRESPONSE._serialized_end=3491
  _SENDPAYRESPONSE_SENDPAYSTATUS._serialized_start=3329
  _SENDPAYRESPONSE_SENDPAYSTATUS._serialized_end=3371
  _SENDPAYROUTE._serialized_start=3493
  _SENDPAYROUTE._serialized_end=3585
  _LISTCHANNELSREQUEST._serialized_start=3588
  _LISTCHANNELSREQUEST._serialized_end=3735
  _LISTCHANNELSRESPONSE._serialized_start=3737
  _LISTCHANNELSRESPONSE._serialized_end=3804
  _LISTCHANNELSCHANNELS._serialized_start=3807
  _LISTCHANNELSCHANNELS._serialized_end=4223
  _ADDGOSSIPREQUEST._serialized_start=4225
  _ADDGOSSIPREQUEST._serialized_end=4260
  _ADDGOSSIPRESPONSE._serialized_start=4262
  _ADDGOSSIPRESPONSE._serialized_end=4281
  _AUTOCLEANINVOICEREQUEST._serialized_start=4283
  _AUTOCLEANINVOICEREQUEST._serialized_end=4394
  _AUTOCLEANINVOICERESPONSE._serialized_start=4397
  _AUTOCLEANINVOICERESPONSE._serialized_end=4526
  _CHECKMESSAGEREQUEST._serialized_start=4528
  _CHECKMESSAGEREQUEST._serialized_end=4613
  _CHECKMESSAGERESPONSE._serialized_start=4615
  _CHECKMESSAGERESPONSE._serialized_end=4671
  _CLOSEREQUEST._serialized_start=4674
  _CLOSEREQUEST._serialized_end=4990
  _CLOSERESPONSE._serialized_start=4993
  _CLOSERESPONSE._serialized_end=5164
  _CLOSERESPONSE_CLOSETYPE._serialized_start=5095
  _CLOSERESPONSE_CLOSETYPE._serialized_end=5148
  _CONNECTREQUEST._serialized_start=5166
  _CONNECTREQUEST._serialized_end=5250
  _CONNECTRESPONSE._serialized_start=5253
  _CONNECTRESPONSE._serialized_end=5395
  _CONNECTRESPONSE_CONNECTDIRECTION._serialized_start=5360
  _CONNECTRESPONSE_CONNECTDIRECTION._serialized_end=5395
  _CONNECTADDRESS._serialized_start=5398
  _CONNECTADDRESS._serialized_end=5649
  _CONNECTADDRESS_CONNECTADDRESSTYPE._serialized_start=5537
  _CONNECTADDRESS_CONNECTADDRESSTYPE._serialized_end=5617
  _CREATEINVOICEREQUEST._serialized_start=5651
  _CREATEINVOICEREQUEST._serialized_end=5725
  _CREATEINVOICERESPONSE._serialized_start=5728
  _CREATEINVOICERESPONSE._serialized_end=6355
  _CREATEINVOICERESPONSE_CREATEINVOICESTATUS._serialized_start=6155
  _CREATEINVOICERESPONSE_CREATEINVOICESTATUS._serialized_end=6211
  _DATASTOREREQUEST._serialized_start=6358
  _DATASTOREREQUEST._serialized_end=6666
  _DATASTOREREQUEST_DATASTOREMODE._serialized_start=6511
  _DATASTOREREQUEST_DATASTOREMODE._serialized_end=6623
  _DATASTORERESPONSE._serialized_start=6669
  _DATASTORERESPONSE._serialized_end=6799
  _CREATEONIONREQUEST._serialized_start=6802
  _CREATEONIONREQUEST._serialized_end=6959
  _CREATEONIONRESPONSE._serialized_start=6961
  _CREATEONIONRESPONSE._serialized_end=7021
  _CREATEONIONHOPS._serialized_start=7023
  _CREATEONIONHOPS._serialized_end=7073
  _DELDATASTOREREQUEST._serialized_start=7075
  _DELDATASTOREREQUEST._serialized_end=7149
  _DELDATASTORERESPONSE._serialized_start=7152
  _DELDATASTORERESPONSE._serialized_end=7285
  _DELEXPIREDINVOICEREQUEST._serialized_start=7287
  _DELEXPIREDINVOICEREQUEST._serialized_end=7359
  _DELEXPIREDINVOICERESPONSE._serialized_start=7361
  _DELEXPIREDINVOICERESPONSE._serialized_end=7388
  _DELINVOICEREQUEST._serialized_start=7391
  _DELINVOICEREQUEST._serialized_end=7573
  _DELINVOICEREQUEST_DELINVOICESTATUS._serialized_start=7507
  _DELINVOICEREQUEST_DELINVOICESTATUS._serialized_end=7560
  _DELINVOICERESPONSE._serialized_start=7576
  _DELINVOICERESPONSE._serialized_end=8015
  _DELINVOICERESPONSE_DELINVOICESTATUS._serialized_start=7507
  _DELINVOICERESPONSE_DELINVOICESTATUS._serialized_end=7560
  _INVOICEREQUEST._serialized_start=8018
  _INVOICEREQUEST._serialized_end=8330
  _INVOICERESPONSE._serialized_start=8333
  _INVOICERESPONSE._serialized_end=8692
  _LISTDATASTOREREQUEST._serialized_start=8694
  _LISTDATASTOREREQUEST._serialized_end=8729
  _LISTDATASTORERESPONSE._serialized_start=8731
  _LISTDATASTORERESPONSE._serialized_end=8802
  _LISTDATASTOREDATASTORE._serialized_start=8805
  _LISTDATASTOREDATASTORE._serialized_end=8940
  _LISTINVOICESREQUEST._serialized_start=8943
  _LISTINVOICESREQUEST._serialized_end=9112
  _LISTINVOICESRESPONSE._serialized_start=9114
  _LISTINVOICESRESPONSE._serialized_end=9181
  _LISTINVOICESINVOICES._serialized_start=9184
  _LISTINVOICESINVOICES._serialized_end=9844
  _LISTINVOICESINVOICES_LISTINVOICESINVOICESSTATUS._serialized_start=9621
  _LISTINVOICESINVOICES_LISTINVOICESINVOICESSTATUS._serialized_end=9684
  _SENDONIONREQUEST._serialized_start=9847
  _SENDONIONREQUEST._serialized_end=10195
  _SENDONIONRESPONSE._serialized_start=10198
  _SENDONIONRESPONSE._serialized_end=10721
  _SENDONIONRESPONSE_SENDONIONSTATUS._serialized_start=10569
  _SENDONIONRESPONSE_SENDONIONSTATUS._serialized_end=10613
  _SENDONIONFIRST_HOP._serialized_start=10723
  _SENDONIONFIRST_HOP._serialized_end=10804
  _LISTSENDPAYSREQUEST._serialized_start=10807
  _LISTSENDPAYSREQUEST._serialized_end=11042
  _LISTSENDPAYSREQUEST_LISTSENDPAYSSTATUS._serialized_start=10944
  _LISTSENDPAYSREQUEST_LISTSENDPAYSSTATUS._serialized_end=11003
  _LISTSENDPAYSRESPONSE._serialized_start=11044
  _LISTSENDPAYSRESPONSE._serialized_end=11111
  _LISTSENDPAYSPAYMENTS._serialized_start=11114
  _LISTSENDPAYSPAYMENTS._serialized_end=11727
  _LISTSENDPAYSPAYMENTS_LISTSENDPAYSPAYMENTSSTATUS._serialized_start=11532
  _LISTSENDPAYSPAYMENTS_LISTSENDPAYSPAYMENTSSTATUS._serialized_end=11599
  _LISTTRANSACTIONSREQUEST._serialized_start=11729
  _LISTTRANSACTIONSREQUEST._serialized_end=11754
  _LISTTRANSACTIONSRESPONSE._serialized_start=11756
  _LISTTRANSACTIONSRESPONSE._serialized_end=11839
  _LISTTRANSACTIONSTRANSACTIONS._serialized_start=11842
  _LISTTRANSACTIONSTRANSACTIONS._serialized_end=12124
  _LISTTRANSACTIONSTRANSACTIONSINPUTS._serialized_start=12127
  _LISTTRANSACTIONSTRANSACTIONSINPUTS._serialized_end=12643
  _LISTTRANSACTIONSTRANSACTIONSINPUTS_LISTTRANSACTIONSTRANSACTIONSINPUTSTYPE._serialized_start=12339
  _LISTTRANSACTIONSTRANSACTIONSINPUTS_LISTTRANSACTIONSTRANSACTIONSINPUTSTYPE._serialized_end=12617
  _LISTTRANSACTIONSTRANSACTIONSOUTPUTS._serialized_start=12646
  _LISTTRANSACTIONSTRANSACTIONSOUTPUTS._serialized_end=13190
  _LISTTRANSACTIONSTRANSACTIONSOUTPUTS_LISTTRANSACTIONSTRANSACTIONSOUTPUTSTYPE._serialized_start=12885
  _LISTTRANSACTIONSTRANSACTIONSOUTPUTS_LISTTRANSACTIONSTRANSACTIONSOUTPUTSTYPE._serialized_end=13164
  _PAYREQUEST._serialized_start=13193
  _PAYREQUEST._serialized_end=13665
  _PAYRESPONSE._serialized_start=13668
  _PAYRESPONSE._serialized_end=14047
  _PAYRESPONSE_PAYSTATUS._serialized_start=13950
  _PAYRESPONSE_PAYSTATUS._serialized_end=14000
  _LISTNODESREQUEST._serialized_start=14049
  _LISTNODESREQUEST._serialized_end=14091
  _LISTNODESRESPONSE._serialized_start=14093
  _LISTNODESRESPONSE._serialized_end=14148
  _LISTNODESNODES._serialized_start=14151
  _LISTNODESNODES._serialized_end=14376
  _LISTNODESNODESADDRESSES._serialized_start=14379
  _LISTNODESNODESADDRESSES._serialized_end=14626
  _LISTNODESNODESADDRESSES_LISTNODESNODESADDRESSESTYPE._serialized_start=14519
  _LISTNODESNODESADDRESSES_LISTNODESNODESADDRESSESTYPE._serialized_end=14614
  _WAITANYINVOICEREQUEST._serialized_start=14628
  _WAITANYINVOICEREQUEST._serialized_end=14731
  _WAITANYINVOICERESPONSE._serialized_start=14734
  _WAITANYINVOICERESPONSE._serialized_end=15265
  _WAITANYINVOICERESPONSE_WAITANYINVOICESTATUS._serialized_start=15110
  _WAITANYINVOICERESPONSE_WAITANYINVOICESTATUS._serialized_end=15155
  _WAITINVOICEREQUEST._serialized_start=15267
  _WAITINVOICEREQUEST._serialized_end=15302
  _WAITINVOICERESPONSE._serialized_start=15305
  _WAITINVOICERESPONSE._serialized_end=15824
  _WAITINVOICERESPONSE_WAITINVOICESTATUS._serialized_start=15672
  _WAITINVOICERESPONSE_WAITINVOICESTATUS._serialized_end=15714
  _WAITSENDPAYREQUEST._serialized_start=15827
  _WAITSENDPAYREQUEST._serialized_end=15969
  _WAITSENDPAYRESPONSE._serialized_start=15972
  _WAITSENDPAYRESPONSE._serialized_end=16490
  _WAITSENDPAYRESPONSE_WAITSENDPAYSTATUS._serialized_start=16349
  _WAITSENDPAYRESPONSE_WAITSENDPAYSTATUS._serialized_end=16382
  _NEWADDRREQUEST._serialized_start=16493
  _NEWADDRREQUEST._serialized_end=16651
  _NEWADDRREQUEST_NEWADDRADDRESSTYPE._serialized_start=16577
  _NEWADDRREQUEST_NEWADDRADDRESSTYPE._serialized_end=16635
  _NEWADDRRESPONSE._serialized_start=16653
  _NEWADDRRESPONSE._serialized_end=16744
  _WITHDRAWREQUEST._serialized_start=16747
  _WITHDRAWREQUEST._serialized_end=16949
  _WITHDRAWRESPONSE._serialized_start=16951
  _WITHDRAWRESPONSE._serialized_end=17009
  _KEYSENDREQUEST._serialized_start=17012
  _KEYSENDREQUEST._serialized_end=17344
  _KEYSENDRESPONSE._serialized_start=17347
  _KEYSENDRESPONSE._serialized_end=17717
  _KEYSENDRESPONSE_KEYSENDSTATUS._serialized_start=17641
  _KEYSENDRESPONSE_KEYSENDSTATUS._serialized_end=17670
  _KEYSENDEXTRATLVS._serialized_start=17719
  _KEYSENDEXTRATLVS._serialized_end=17737
  _FUNDPSBTREQUEST._serialized_start=17740
  _FUNDPSBTREQUEST._serialized_end=18051
  _FUNDPSBTRESPONSE._serialized_start=18054
  _FUNDPSBTRESPONSE._serialized_end=18271
  _FUNDPSBTRESERVATIONS._serialized_start=18273
  _FUNDPSBTRESERVATIONS._serialized_end=18390
  _SENDPSBTREQUEST._serialized_start=18392
  _SENDPSBTREQUEST._serialized_end=18457
  _SENDPSBTRESPONSE._serialized_start=18459
  _SENDPSBTRESPONSE._serialized_end=18503
  _SIGNPSBTREQUEST._serialized_start=18505
  _SIGNPSBTREQUEST._serialized_end=18554
  _SIGNPSBTRESPONSE._serialized_start=18556
  _SIGNPSBTRESPONSE._serialized_end=18595
  _UTXOPSBTREQUEST._serialized_start=18598
  _UTXOPSBTREQUEST._serialized_end=18945
  _UTXOPSBTRESPONSE._serialized_start=18948
  _UTXOPSBTRESPONSE._serialized_end=19165
  _UTXOPSBTRESERVATIONS._serialized_start=19167
  _UTXOPSBTRESERVATIONS._serialized_end=19284
  _TXDISCARDREQUEST._serialized_start=19286
  _TXDISCARDREQUEST._serialized_end=19318
  _TXDISCARDRESPONSE._serialized_start=19320
  _TXDISCARDRESPONSE._serialized_end=19374
  _TXPREPAREREQUEST._serialized_start=19377
  _TXPREPAREREQUEST._serialized_end=19541
  _TXPREPARERESPONSE._serialized_start=19543
  _TXPREPARERESPONSE._serialized_end=19611
  _TXSENDREQUEST._serialized_start=19613
  _TXSENDREQUEST._serialized_end=19642
  _TXSENDRESPONSE._serialized_start=19644
  _TXSENDRESPONSE._serialized_end=19700
  _DISCONNECTREQUEST._serialized_start=19702
  _DISCONNECTREQUEST._serialized_end=19763
  _DISCONNECTRESPONSE._serialized_start=19765
  _DISCONNECTRESPONSE._serialized_end=19785
  _FEERATESREQUEST._serialized_start=19787
  _FEERATESREQUEST._serialized_end=19894
  _FEERATESREQUEST_FEERATESSTYLE._serialized_start=19857
  _FEERATESREQUEST_FEERATESSTYLE._serialized_end=19894
  _FEERATESRESPONSE._serialized_start=19896
  _FEERATESRESPONSE._serialized_end=19982
  _FEERATESPERKB._serialized_start=19985
  _FEERATESPERKB._serialized_end=20308
  _FEERATESPERKW._serialized_start=20311
  _FEERATESPERKW._serialized_end=20634
  _FEERATESONCHAIN_FEE_ESTIMATES._serialized_start=20637
  _FEERATESONCHAIN_FEE_ESTIMATES._serialized_end=20830
  _FUNDCHANNELREQUEST._serialized_start=20833
  _FUNDCHANNELREQUEST._serialized_end=21271
  _FUNDCHANNELRESPONSE._serialized_start=21274
  _FUNDCHANNELRESPONSE._serialized_end=21429
  _GETROUTEREQUEST._serialized_start=21432
  _GETROUTEREQUEST._serialized_end=21668
  _GETROUTERESPONSE._serialized_start=21670
  _GETROUTERESPONSE._serialized_end=21723
  _GETROUTEROUTE._serialized_start=21726
  _GETROUTEROUTE._serialized_end=21923
  _GETROUTEROUTE_GETROUTEROUTESTYLE._serialized_start=21894
  _GETROUTEROUTE_GETROUTEROUTESTYLE._serialized_end=21923
  _LISTFORWARDSREQUEST._serialized_start=21926
  _LISTFORWARDSREQUEST._serialized_end=22184
  _LISTFORWARDSREQUEST_LISTFORWARDSSTATUS._serialized_start=22066
  _LISTFORWARDSREQUEST_LISTFORWARDSSTATUS._serialized_end=22142
  _LISTFORWARDSRESPONSE._serialized_start=22186
  _LISTFORWARDSRESPONSE._serialized_end=22253
  _LISTFORWARDSFORWARDS._serialized_start=22256
  _LISTFORWARDSFORWARDS._serialized_end=22824
  _LISTFORWARDSFORWARDS_LISTFORWARDSFORWARDSSTATUS._serialized_start=22621
  _LISTFORWARDSFORWARDS_LISTFORWARDSFORWARDSSTATUS._serialized_end=22705
  _LISTFORWARDSFORWARDS_LISTFORWARDSFORWARDSSTYLE._serialized_start=22707
  _LISTFORWARDSFORWARDS_LISTFORWARDSFORWARDSSTYLE._serialized_end=22755
  _LISTPAYSREQUEST._serialized_start=22827
  _LISTPAYSREQUEST._serialized_end=23046
  _LISTPAYSREQUEST_LISTPAYSSTATUS._serialized_start=22952
  _LISTPAYSREQUEST_LISTPAYSSTATUS._serialized_end=23007
  _LISTPAYSRESPONSE._serialized_start=23048
  _LISTPAYSRESPONSE._serialized_end=23099
  _LISTPAYSPAYS._serialized_start=23102
  _LISTPAYSPAYS._serialized_end=23611
  _LISTPAYSPAYS_LISTPAYSPAYSSTATUS._serialized_start=23436
  _LISTPAYSPAYS_LISTPAYSPAYSSTATUS._serialized_end=23495
  _PINGREQUEST._serialized_start=23613
  _PINGREQUEST._serialized_end=23702
  _PINGRESPONSE._serialized_start=23704
  _PINGRESPONSE._serialized_end=23734
  _SIGNMESSAGEREQUEST._serialized_start=23736
  _SIGNMESSAGEREQUEST._serialized_end=23773
  _SIGNMESSAGERESPONSE._serialized_start=23775
  _SIGNMESSAGERESPONSE._serialized_end=23845
  _STOPREQUEST._serialized_start=23847
  _STOPREQUEST._serialized_end=23860
  _STOPRESPONSE._serialized_start=23862
  _STOPRESPONSE._serialized_end=23876
  _NODE._serialized_start=23879
  _NODE._serialized_end=26807
>>>>>>> a0b3bff3d (1/n: pr resurrection)
# @@protoc_insertion_point(module_scope)
